### ISSUE TITLE
Grammatical mistake correction

### ISSUE THREAD

**Issue by NeumoNeumo** [IceLocke/CS205-2023Fall-Assignment3-Memory-Pool#1]
It seems that there is a sentence with a grammatical problem in your `README.md`

> In fact, for `mmpool` entries those are created when all the previous `mmpool` entries don't have enough space

which should probably be 

> In fact, for those `mmpool` entries that are created ...

**Comment by IceLocke** [comment]
Thank you for your revision. Please make a pull request.
